# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fa361a9a5d43aaa8e3455e3f0892fb22d74c591cddac1f86d2a0a12431ca2d81c90238828359efe9bc05b7ef2fba968b11e102345c0edbe352826a4ded348b0

test:
  secret_key_base: 23a7b545aae0ed2b7d5a72604ad931cf598589bdddb3c915d437a9c59a999471a5e2bdcfba7d77dfef717232904da951267661073688c66ee76ab2f185592466

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
